// Generated by scripts/fetch-hexa-job.mjs — source: MapleStory Wiki.
export default {
  "id": "arch-mage-il",
  "name": "Arch Mage (Ice, Lightning)",
  "aliases": [
    "Arch Mage (I/L)",
    "Arch Mage (Ice/Lightning)",
    "Ice/Lightning Arch Mage",
    "I/L Arch Mage"
  ],
  "wikiPage": "Arch Mage (Ice, Lightning)/Skills",
  "nodes": {
    "skill-1": {
      "name": "Frozen Lightning",
      "icon": "frozen-lightning.png",
      "skills": [
        {
          "name": "Frozen Lightning",
          "icon": "frozen-lightning.png"
        }
      ]
    },
    "skill-2": {
      "name": "Parabolic Bolt",
      "icon": "parabolic-bolt.png",
      "skills": [
        {
          "name": "Parabolic Bolt",
          "icon": "parabolic-bolt.png"
        }
      ]
    },
    "mastery-1": {
      "name": "HEXA Chain Lightning",
      "icon": "hexa-chain-lightning.png",
      "skills": [
        {
          "name": "HEXA Chain Lightning",
          "icon": "hexa-chain-lightning.png"
        }
      ]
    },
    "mastery-2": {
      "name": "HEXA Frozen Orb",
      "icon": "hexa-frozen-orb.png",
      "skills": [
        {
          "name": "HEXA Frozen Orb",
          "icon": "hexa-frozen-orb.png"
        },
        {
          "name": "HEXA Blizzard",
          "icon": "hexa-blizzard.png"
        }
      ]
    },
    "mastery-3": {
      "name": "HEXA Lightning Orb",
      "icon": "hexa-lightning-orb.png",
      "skills": [
        {
          "name": "HEXA Lightning Orb",
          "icon": "hexa-lightning-orb.png"
        },
        {
          "name": "Cryo Shock",
          "icon": "cryo-shock.png"
        }
      ]
    },
    "mastery-4": {
      "name": "HEXA Thunder Sphere",
      "icon": "hexa-thunder-sphere.png",
      "skills": [
        {
          "name": "HEXA Thunder Sphere",
          "icon": "hexa-thunder-sphere.png"
        },
        {
          "name": "HEXA Elquines",
          "icon": "hexa-elquines.png"
        }
      ]
    },
    "boost-1": {
      "name": "Frost Ark Boost",
      "icon": "frost-ark.png",
      "skills": [
        {
          "name": "Frost Ark Boost",
          "icon": "frost-ark.png"
        }
      ]
    },
    "boost-2": {
      "name": "Bolt Barrage Boost",
      "icon": "bolt-barrage.png",
      "skills": [
        {
          "name": "Bolt Barrage Boost",
          "icon": "bolt-barrage.png"
        }
      ]
    },
    "boost-3": {
      "name": "Spirit of Snow Boost",
      "icon": "spirit-of-snow.png",
      "skills": [
        {
          "name": "Spirit of Snow Boost",
          "icon": "spirit-of-snow.png"
        }
      ]
    },
    "boost-4": {
      "name": "Jupiter Thunder Boost",
      "icon": "jupiter-thunder.png",
      "skills": [
        {
          "name": "Jupiter Thunder Boost",
          "icon": "jupiter-thunder.png"
        }
      ]
    },
    "solJanus-1": {
      "name": "Sol Janus",
      "icon": "sol-janus.png",
      "skills": [
        {
          "name": "Sol Janus",
          "icon": "sol-janus.png"
        }
      ]
    },
    "solJanus-2": {
      "name": "Sol Hecate",
      "icon": "sol-hecate.png",
      "icons": [
        { "min": 0, "icon": "sol-hecate.png" },
        { "min": 20, "icon": "sol-hecate-2.png" },
        { "min": 30, "icon": "sol-hecate-3.png" }
      ],
      "skills": [
        {
          "name": "Sol Hecate",
          "icon": "sol-hecate.png"
        }
      ]
    }
  }
}
