// Generated by scripts/build-item-catalog.mjs - do not edit by hand.
// Source: maplestory.io GMS v255. Levels are the in-game
// required levels, which is the only item property Star Force math needs.

const icons = import.meta.glob('../assets/items/*.png', {
  eager: true,
  import: 'default',
})

const CDN = 'https://maplestory.io/api/GMS/255/item'

const iconFor = (id) => icons[`../assets/items/${id}.png`] ?? `${CDN}/${id}/icon`

const RAW_GROUPS = [
  {
    id: 'cra',
    label: 'Chaos Root Abyss',
    items: [
      { id: 1003797, name: "Royal Warrior Helm", level: 150, slot: "Hat" },
      { id: 1042254, name: "Eagle Eye Warrior Armor", level: 150, slot: "Top" },
      { id: 1062165, name: "Trixter Warrior Pants", level: 150, slot: "Bottom" },
      { id: 1302275, name: "Fafnir Mistilteinn", level: 150, slot: "One-Handed Sword" },
    ],
  },
  {
    id: 'absolab',
    label: 'AbsoLab',
    items: [
      { id: 1004422, name: "AbsoLab Knight Helm", level: 160, slot: "Hat" },
      { id: 1052882, name: "AbsoLab Knight Suit", level: 160, slot: "Overall" },
      { id: 1102775, name: "AbsoLab Knight Cape", level: 160, slot: "Cape" },
      { id: 1082636, name: "AbsoLab Knight Gloves", level: 160, slot: "Glove" },
      { id: 1073030, name: "AbsoLab Knight Shoes", level: 160, slot: "Shoes" },
      { id: 1152174, name: "AbsoLab Knight Shoulder", level: 160, slot: "Shoulder Accessory" },
      { id: 1302333, name: "AbsoLab Saber", level: 160, slot: "One-Handed Sword" },
    ],
  },
  {
    id: 'arcane',
    label: 'Arcane Umbra',
    items: [
      { id: 1004808, name: "Arcane Umbra Knight Hat", level: 200, slot: "Hat" },
      { id: 1053063, name: "Arcane Umbra Knight Suit", level: 200, slot: "Overall" },
      { id: 1102940, name: "Arcane Umbra Knight Cape", level: 200, slot: "Cape" },
      { id: 1082695, name: "Arcane Umbra Knight Gloves", level: 200, slot: "Glove" },
      { id: 1073158, name: "Arcane Umbra Knight Shoes", level: 200, slot: "Shoes" },
      { id: 1152196, name: "Arcane Umbra Knight Shoulder", level: 200, slot: "Shoulder Accessory" },
      { id: 1302343, name: "Arcane Umbra Saber", level: 200, slot: "One-Handed Sword" },
    ],
  },
  {
    id: 'eternal',
    label: 'Eternal',
    items: [
      { id: 1005980, name: "Eternal Knight Helm", level: 250, slot: "Hat" },
      { id: 1042433, name: "Eternal Knight Armor", level: 250, slot: "Top" },
      { id: 1062285, name: "Eternal Knight Pants", level: 250, slot: "Bottom" },
      { id: 1103433, name: "Eternal Knight Cape", level: 250, slot: "Cape" },
      { id: 1082760, name: "Eternal Knight Gloves", level: 250, slot: "Glove" },
      { id: 1073629, name: "Eternal Knight Shoes", level: 250, slot: "Shoes" },
      { id: 1152212, name: "Eternal Knight Shoulder", level: 250, slot: "Shoulder Accessory" },
    ],
  },
  {
    id: 'genesis',
    label: 'Genesis',
    items: [
      { id: 1302355, name: "Genesis Saber", level: 200, slot: "One-Handed Sword" },
      { id: 1182285, name: "Genesis Badge", level: 200, slot: "Badge" },
    ],
  },
  {
    id: 'accessory',
    label: 'Accessories',
    items: [
      { id: 1182087, name: "Crystal Ventus Badge", level: 130, slot: "Badge" },
      { id: 1092087, name: "Deimos Warrior Shield", level: 130, slot: "Shield" },
      { id: 1012757, name: "Twilight Mark", level: 140, slot: "Face Accessory" },
      { id: 1122150, name: "Dominator Pendant", level: 140, slot: "Pendant" },
      { id: 1022277, name: "Papulatus Mark", level: 145, slot: "Eye Decoration" },
      { id: 1113075, name: "Superior Gollux Ring", level: 150, slot: "Ring" },
      { id: 1032223, name: "Superior Gollux Earrings", level: 150, slot: "Earrings" },
      { id: 1122267, name: "Superior Engraved Gollux Pendant", level: 150, slot: "Pendant" },
      { id: 1132246, name: "Superior Engraved Gollux Belt", level: 150, slot: "Belt" },
      { id: 1012632, name: "Berserked", level: 160, slot: "Face Accessory" },
      { id: 1012438, name: "Sweetwater Tattoo", level: 160, slot: "Face Accessory" },
      { id: 1022211, name: "Sweetwater Monocle", level: 160, slot: "Eye Decoration" },
      { id: 1032330, name: "Estella Earrings", level: 160, slot: "Earrings" },
      { id: 1122430, name: "Source of Suffering", level: 160, slot: "Pendant" },
      { id: 1113313, name: "Guardian Angel Ring", level: 160, slot: "Ring" },
      { id: 1182273, name: "Sengoku Hakase Badge", level: 160, slot: "Badge", maxStar: 22 },
      { id: 1032316, name: "Commanding Force Earring", level: 200, slot: "Earrings" },
      { id: 1113306, name: "Endless Terror", level: 200, slot: "Ring" },
      { id: 1113341, name: "Whisper of the Source", level: 250, slot: "Ring" },
    ],
  },
]

export const ITEM_GROUPS = RAW_GROUPS.map((group) => ({
  ...group,
  items: group.items.map((item) => ({ ...item, icon: iconFor(item.id) })),
}))

export const ITEMS = ITEM_GROUPS.flatMap((group) => group.items)

const BY_ID = new Map(ITEMS.map((item) => [item.id, item]))

export const findItemById = (id) => BY_ID.get(id)
